# Generated by Django 3.0.5 on 2022-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221115_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='no_ticket',
        ),
        migrations.AddField(
            model_name='buyer',
            name='no_ticket',
            field=models.IntegerField(null=True),
        ),
    ]
