# Generated by Django 3.0.5 on 2022-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_buyer_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='amount_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
