# Generated by Django 3.0.5 on 2022-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221115_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
